swagger: '2.0'
info:
  title: 'Login API'
  description: 'API for user login'
  version: '1.0'
paths:
  /login:
    post:
      summary: 'Get access token for authentication'
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: 'User login data'
          required: true
          schema:
            type: object
            properties:
              username:
                type: string
                description: 'Username for login'
              password:
                type: string
                description: 'Password for login'
            required:
              - username
              - password
      responses:
        200:
          description: 'Access token obtained successfully'
        401:
          description: 'Invalid credentials'
