swagger: '2.0'
info:
  title: 'Register API'
  description: 'API for user registration'
  version: '1.0'
paths:
  /register:
    post:
      summary: 'Register a new user'
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: 'User registration data'
          required: true
          schema:
            type: object
            properties:
              username:
                type: string
                description: 'Username for registration'
              password:
                type: string
                description: 'Password for registration'
            required:
              - username
              - password
      responses:
        201:
          description: 'User registered successfully'
        400:
          description: 'Missing username or password or Username already taken'
